-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- See: https://www.lazyvim.org/keymaps
-- Add any additional keymaps here
--
-- default <leader> is <space>
-- default <localleader> is `\` (localleader is language-specific leader key)
